name: Go
on: [push]
jobs:

  setup:
    name: Set up
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.12.7
      uses: actions/setup-go@v1
      with:
        go-version: 1.12.7
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Get dependencies
      run: go mod download

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Test
      run: go test -v ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Build
      run: go build -v ./...
