name: Go
on:
  push:
    branches:
      - refs/tags/*
jobs:

  goreleaser:
    name: Set up
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.12.7
      uses: actions/setup-go@v1
      with:
        go-version: 1.12.7
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@master
      with:
        version: latest
        args: release --skip-publish
